# Generated by Django 5.1.3 on 2024-12-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(7, '7º Classe'), (8, '8º Classe'), (9, '9º Classe'), (10, '10º Classe'), (11, '11º Classe'), (12, '12º Classe')], unique=True)),
            ],
        ),
    ]
