# Generated by Django 5.1.3 on 2024-12-03 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('carga_horaria', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('area', models.CharField(choices=[('CD', 'Ciências com Desenho'), ('AM', 'Letra'), ('CB', 'Ciências com Biológia'), ('LB', 'Letras com Biológia')], max_length=20)),
                ('semestre_recomendado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('optativa', models.BooleanField(default=False)),
                ('classe', models.ManyToManyField(related_name='disciplinas', to='classe.classe')),
            ],
        ),
    ]
